[package]
name = "budget-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = "4.5.40"
clearscreen = "4.0.2"
console = "0.16.0"
dialoguer = "0.11.0"
rusqlite = "0.36.0"
thiserror = "2.0.12"
